version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: legal_assistant_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: legaldb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
